### ISSUE TITLE
Site not found 

### ISSUE THREAD

**Issue by oleoneto** [flowck/angolan-on-github#2]
The URL http://github.angodev.com/ does not resolve to a working site.

**Comment by flowck** [comment]
Hi @oleoneto, I will point the domain to this repo soon. I'll let you know.

**Comment by oleoneto** [comment]
Cool beans! Nice work, by the way!

**Comment by flowck** [comment]
Hi @oleoneto you can check now http://github.angodev.com/.

**Comment by oleoneto** [comment]
Nice! Very cool.
